#include "story_node9-b.h"

void node9(int *score, char* player, Address *p)
{
    Sentence word_input;
    boolean validinput;
    int input;
    printf("Megumi: \"Aku kelihatan sedih ya?\"");START();system("cls");
    printf("%s: \"Aku lihat kok, kamu pas sampai ke game cafe tadi kamu habis nangis\"", player);START();system("cls");
    printf("%s: \"Kamu kalo ada masalah apa gitu, ceritain aja\"", player);START();system("cls");
    printf("Megumi: \"uuun, enggak apa-apa kok, tadi sebelum ke sini, aku nonton drakor sedih\"");START();system("cls");
    printf("(aku tahu bahwa dia sedang berbohong)");START();system("cls");
    printf("%s: \"Oke deh, kalo gitu sepertinya masih baik-baik aja\"", player);START();system("cls");
    printf("%s: \"Gimana nilai matematikamu?\"", player);START();system("cls");
    printf("Megumi: \"untungnya dapet bagus. makasih buat tutornya kemarin hehehe.\"");START();system("cls");
    printf("Megumi: \"Enaknya punya temen pinter kaya kamu\"");START();system("cls");
    printf("Megumi: \"T-Tapi bukan berarti aku cuma manfaatin kamu ya, ingat itu\"");START();system("cls");
    printf("%s: \"Iya, iya. Aku paham kok\"", player);START();system("cls");
    printf("Kita membicarakan banyak hal selama perjalanan pulang");START();system("cls");
    printf("Akhirnya tiba di rumah");START();system("cls");
    printf("Megumi: \"%s, aku duluan ya. Selamat Malam\"", player);START();system("cls");
    printf("%s: \"Selamat malam, Megumi.\"", player);START();system("cls");
    printf("Keesokannya, kita berangkat bersama ke Game center");START();system("cls");
    printf("kami pertama kali mencoba Mesin Gachapon");START();system("cls");
    printf("Megumi: \"Ayo main gacha\"");START();system("cls");
    printf("%s: \"Oke, tapi 5 koin aja ya. Kecanduan gacha tidak baik ya, Megumi.\"", player);START();system("cls");
    printf("Megumi: \"baik, baik\"");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
}