#include "story_node7-8.h"

void node7(int *score, char* player, Address *p)    {
    Sentence word_input;
    int input;
    boolean validinput;
    printf("Aku menerima pernyataan cinta Miya.");START();system("cls");
    printf("Aku pun memeluk Miya.");START();system("cls");
    printf("di saat ini, ini adalah momen paling berharga dalam hidup.");START();system("cls");
    printf("dia memejamkan mata, memberi isyarat padaku untuk melakukan sesuatu.");START();system("cls");
    printf("Wajahku mulai mendekati wajahnya.");START();system("cls");
    printf("lalu kucium bibir itu, rasa lembut yang tidak terlupakan.");START();system("cls");
    printf("namun beberapa saat kemudian, dia mulai menitihkan air mata, dan menangis.");START();system("cls");
    printf("%s: \"Kamu kenapa, Miya?\"", player);START();system("cls");
    printf("Miya: \"Maaf, maafkan aku, %s. Maaf.\"", player);START();system("cls");
    printf("Aku pun kebingungan. aku berusahan menenangkan Miya.");START();system("cls");
    printf("setelah turun dari Gondala, dia sudah mulai tenang.");START();system("cls");
    printf("dia berjalan ke depan, kemudian berbalik melihatku.");START();system("cls");
    printf("dia sambil tersenyum dan mengatakan,");START();system("cls");
    printf("Miya: \"Terima kasih banyak, %s. ini merupakan hadiah terbaik yang pernah kamu berikan kepadaku.\"", player);START();system("cls");
    printf("%s: \"Ya!\"", player);START();system("cls");
    printf("seminggu setelahnya, aku mulai jarang melihat Miya di sekolah.");START();system("cls");
    printf("awalnya cuma sehari saja, namun sekarang ia jarang ke sekolah.");START();system("cls");
    printf("dua minggu setelah peristiwa itu, aku mulai mencari tahu");START();system("cls");
    printf("aku yang cemas pun menghampiri Bu Kumakawa.");START();system("cls");
    printf("saat mengunjungi rumahnya, Bu Kumakawa ternyata sedang pergi.");START();system("cls");
    printf("aku pun menelpon Bu Kumakawa.");START();system("cls");
    printf("Bu Kumakawa pun mengangkat teleponnya");START();system("cls");
    printf("%s: \"Halo, Bu Kumakawa.\"", player);START();system("cls");
    printf("dia berbicara sambil tersedu-sedu.");START();system("cls");
    printf("Bu Kumakawa: \"Maaf %s-chan, kamu harus ke rumah sakit sekarang. Miya sedang dalam situasi gawat.\"", player);START();system("cls");
    printf("aku langsung mengiyakan");START();system("cls");
    printf("%s: \"Baik bu, saya segera ke sana\"", player);START();system("cls");
    printf("Aku segera ngebut menggunakan sepeda motorku");START();system("cls");
    printf("saat sampai di rumah sakit, terdapat Bu Kumakawa dan Suaminya yang sedang sedih. aku segera menghapiri mereka.");START();system("cls");
    printf("%s: \"Bu Kumakawa, Pak Kumakawa, bagaimana kabar Miya?\"", player);START();system("cls");
    printf("Pak Kumakawa: \"Takdir berkata lain, Miya sudah dinyatakan meninggal dunia karena gagal operasi.\"");START();system("cls");
    printf("Aku pun tidak menyangka hal ini akan terjadi pada hidupku.");START();system("cls");
    printf("Air mata mulai membanjiri pipiku. aku tidak menyangka hatiku akan hancur seperti ini, aku tidak bisa menerimanya.");START();system("cls");
    printf("Aku pun mulai menangis. Aku melihat Miya untuk terakhir kalinya. tubuh dia sudah tidak bergerak, nafasnya sudah hilang.");START();system("cls");
    printf("aku pun menempelkan dahi pada wajahnya, ku berbisik.");START();system("cls");
    printf("%s: \"hhmmmp..hmmmp..maafkan aku, Miya-chan. aku tidak ada di sampingmu saat kau sedang berjuang. maafkan aku.\"", player);START();system("cls");
    printf("Aku menggenggam tangan Miya yang sudah diri, dan mengecup tangan itu untuk terakhir kalinya.");START();system("cls");
    printf("selama ini, ia mempunyai kanker, namun ia tidak pernah mengungkapkannya ke siapapun, termasuk aku.");START();system("cls");
    printf("harapan yang ia ucapkan terakhir kali pada saat di taman bermain, merupakan keinginan yang mungkin tidak akan terwujud.");START();system("cls");
    printf("aku berlarut dengan kesedihan");START();system("cls");
    printf("dua hari berlalu. ini adalah hari pemakaman Miya. aku dan teman-teman sekolah mengiringi pemakamannya. prosesi renungan dimulai. Aku yang sambil memegang Abu dari Miya, mulai memberikan harapanku.");START();system("cls");
    printf("%s: \"Semoga kamu tenang di sana, Miya. suatu hari aku juga akan mengikuti jejakmu. sampai jumpa, Miya.\"", player);START();system("cls");
    printf("3 tahun setelahnya..");START();system("cls");
    printf("akhirnya tiba, hari pengumuman tes masuk Universitasku.");START();system("cls");
    printf("Tertulis pada bagian awal e-mail, \"Selamat, Anda diterima di Stanford University Jurusan Computer Science...\"");START();system("cls");
    printf("%s: \"Hore, aku diterima!!\"", player);START();system("cls");
    printf("aku turun ke lantai bawah. memberitahu ke ibuku.");START();system("cls");
    printf("%s: \"Mama, aku diterima di Stanford.\"");START();system("cls");
    printf("Mama: \"Selamat ya, %s. anakku pintar banget.\"", player);START();system("cls");
    printf("%s: \"Hehe, terima kasih, Ma.\"", player);START();system("cls");
    printf("aku menikmati hasil jerih payahku ini, aku juga mendedikasikan usahaku ini demi Miya di sana.");START();system("cls");
    printf("%s: \"(Aku yakin Miya senang dengan hal ini.)\"");START();system("cls");
    printf("The End");START();system("cls");
    *p = LEFT(*p);
}

void node8(int *score, char* player, Address *p)    {
    Sentence word_input;
    int input;
    boolean validinput;
    system("cls");
    printf("Miya: \"Oh, jadi begitu ya\"");START();system("cls");
    printf("%s: \"Maaf\"");START();system("cls");
    printf("Kita pun terdiam canggung");START();system("cls");
    printf("kita pun selesai bermain Gondala.");START();system("cls");
    printf("ia tiba-tiba berkata dengan tegas");START();system("cls");
    printf("Miya: \"Aku mau pulang. aku duluan.\"");START();system("cls");
    printf("Dia pun berlari menjauhiku dengan kencang");START();system("cls");
    printf("Aku tidak tahu harus berkata apa");START();system("cls");
    printf("setelah kejadian itu, ia tidak mau berbicara kepadaku. hubungan pertemananku dengannya sepertinya telah berakhir");START();system("cls");
    score_change(score, -500);
    *p = RIGHT(*p);
    /*
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    printf("");START();system("cls");
    */
}